import turtle  
  
star = turtle.Turtle()
star.speed(0)
star.color("red") 
def move():  
    for i in range(5): 
        star.forward(50) 
        star.right(144) 
for i in range(1,6):
    star.penup()
    star.goto(0,50*i)
    star.pendown()
    move()
    star.penup()
    star.goto(50*i,50*i)
    star.pendown()
    move()
    star.penup()
    star.goto(50*i,0)
    star.pendown()
    move()
    star.penup()
    star.goto(50*i,-50*i)
    star.pendown()
    move()
    star.penup()
    star.goto(0,-50*i)
    star.pendown()
    move()
    star.penup()
    star.goto(-50*i,50*i)
    star.pendown()
    move()
    star.penup()
    star.goto(-50*i,0)
    star.pendown()
    move()
    star.penup()
    star.goto(-50*i,-50*i)
    star.pendown()
    move()


#turtle.done()
